{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rundeck.fullname" . }}-nginx-configmap
  labels: {{ include "rundeck.labels" . | indent 4 }}
data:
  nginx.conf: |-
{{- if .Values.nginxConfOverride }}
{{ tpl .Values.nginxConfOverride . | indent 4 }}
{{- else }}
{{ .Files.Get "files/nginx/nginx.conf" | indent 4 }}
{{- end }}
{{- end -}}