apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rundeck.fullname" . }}-environment-configmap
  labels: {{ include "rundeck.labels" . | indent 4 }}
data:
{{ toYaml .Values.rundeck.env | indent 4}}