{{- if or .Values.rundeck.extraConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rundeck.extraConfigName }}
  labels: {{ include "rundeck.labels" . | indent 4 }}
data:
{{- range $name, $config := .Values.rundeck.extraConfigMap }}
  {{ $name }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}