apiVersion: v1
kind: Service
metadata:
  name: {{ include "rundeck.fullname" . }}
  labels: {{ include "rundeck.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.nginx.enabled }}
      targetPort: http
      {{- else }}
      targetPort: rundeck
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rundeck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
