name: 'release'
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  

jobs:
  # The "build" workflow
  lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.13.2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Lint chart
        run: helm lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install chart
        run: |
          helm install rundeck . -n rundeck --create-namespace --wait

  publish-pr:
    needs: [lint-test]
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request')
    steps:
      - uses: actions/checkout@v2
        with:
          path: rundeck
      - name: Update chart version
        run: |
          #!/bin/sh
          sed -i -E 's/version:(.*)/version: \1-pr${{ github.event.pull_request.number }}/g' rundeck/Chart.yaml
      - uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: rundeck

  publish:
    needs: [lint-test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          path: rundeck
      - uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: rundeck
      




   