name: 'release'
on:
  push:
    branches:
      - main
    tags:
      - '*'
    pull_request:
      branches:
        - main
  

jobs:
  # The "build" workflow
  lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      
      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs .

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing (install)
        run: ct install

  publish-pr:
    needs: [lint-test]
    runs-on: ubuntu-latest
    if: (github.event.issue.pull_request != null)
    steps:
      - name: Update chart version
        run: |
          #!/bin/sh
          sed -iE 's/version:(.*)/version: \1-pr{{ github.event.issue.id }}/g' Chart.yaml
        
      - uses: goodsmileduck/helm-push-action@v2
        env:
          SOURCE_DIR: '.'
          CHART_FOLDER: '.'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}

  publish:
    needs: [lint-test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: goodsmileduck/helm-push-action@v2
        env:
          SOURCE_DIR: '.'
          CHART_FOLDER: '.'
          FORCE: 'False'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      




   